from datetime import datetime
from typing import Protocol

from app.domain.entities import Booking, BookingDetails, Seat, Showtime


class BookingRepository(Protocol):
    def get_showtime(self, showtime_id: int) -> Showtime | None: ...

    def get_seat(self, seat_id: int) -> Seat | None: ...

    def get_by_id(self, booking_id: int) -> Booking | None: ...

    def has_confirmed_booking(self, showtime_id: int, seat_id: int) -> bool: ...

    def create(self, user_id: int, showtime_id: int, seat_id: int) -> Booking: ...

    def list_by_user(self, user_id: int) -> list[BookingDetails]: ...

    def get_details(self, booking_id: int) -> BookingDetails | None: ...

    def cancel(self, booking_id: int, cancelled_at: datetime) -> None: ...
